version: '3'

services:
  nginx:
    image: aeifn/nginx:stable
    depends_on:
      - "app_ru"
      - "app_en"
      - "uploader"
      - "downloader"
      - "sitemap"
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    volumes:
      - ./store:/store:ro
      - sitemap:/sitemap

  mongo:
    image: aeifn/mongo:3.2.22

  redis:
    image: redis:5.0.7

  app_en:
    image: aeifn/pastvu:en
    expose:
      - "3000"
      - "3010" 
      - "3011"
    environment:
      - MODULE=app
    depends_on:
      - "mongo"
      - "redis"
    restart: always
    volumes:
      - ./store:/store
      - ./config:/config

  app_ru:
    image: aeifn/pastvu:stable
    expose:
      - "3000"
      - "3010"
      - "3011"
    environment:
      - MODULE=app
      - LANG=ru
    depends_on:
      - "mongo"
      - "redis"
    restart: always
    volumes:
      - ./store:/store
      - ./config:/config

  uploader:
    image: aeifn/pastvu:stable
    expose:
      - "3001"
    environment:
      - MODULE=uploader
    depends_on:
      - "app_ru"
    restart: always
    volumes:
      - ./store:/store
      - ./config:/config
      
  downloader:
    image: aeifn/pastvu:stable
    expose:
      - "3002"
    environment:
      - MODULE=downloader
    depends_on:
      - "app_ru"
    restart: always
    volumes:
      - ./store:/store:ro
      - ./config:/config
    
  sitemap:
    image: aeifn/pastvu:stable
    environment:
      - MODULE=sitemap
    depends_on:
      - "app_ru"
    restart: always
    volumes:
      - ./config:/config
      - sitemap:/sitemap

volumes:
  sitemap:
