version: '3'

services:

  mongo:
    build: ./mongo

  redis:
    image: redis:5.0.7

  app:
    build: .
    expose:
      - "3010" 
      - "3011"
    environment:
      - MODULE=app
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
      - "redis"
    volumes:
      - ./store:/store
      - ./logs/app:/logs

  uploader:
    build: .
    expose:
      - "3001"
    environment:
      - MODULE=uploader
    depends_on:
      - "app"
    volumes:
      - ./store:/store
      - ./logs/uploader:/logs
      
  downloader:
    build: .
    expose:
      - "3002"
    environment:
      - MODULE=downloader
    depends_on:
      - "app"
    volumes:
      - ./store:/store:ro
      - ./logs/downloader:/logs
    
  sitemap:
    build: .
    environment:
      - MODULE=sitemap
    depends_on:
      - "app"
    volumes:
      - ./logs/sitemap:/logs
