version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - "app_en"
      - "app_ru"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./store:/store:ro

  mongo:
    build: ./mongo

  redis:
    image: redis:5.0.7

  app_en:
    build: .
    expose:
      - "3000"
      - "3010" 
      - "3011"
    environment:
      - MODULE=app
    depends_on:
      - "mongo"
      - "redis"
    volumes:
      - ./store:/store

  app_ru:
    build: .
    expose:
      - "3000"
      - "3010" 
      - "3011"
    environment:
      - MODULE=app
      - LANG=ru
    depends_on:
      - "mongo"
      - "redis"
    volumes:
      - ./store:/store

  uploader:
    build: .
    expose:
      - "3001"
    environment:
      - MODULE=uploader
    depends_on:
      - "app_en"
    volumes:
      - ./store:/store
      
  downloader:
    build: .
    expose:
      - "3002"
    environment:
      - MODULE=downloader
    depends_on:
      - "app_en"
    volumes:
      - ./store:/store:ro
    
  sitemap:
    build: .
    environment:
      - MODULE=sitemap
    depends_on:
      - "app_en"
