version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - "app_en"
      - "app_ru"
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    volumes:
      - ./store:/store:ro
      - ./logs/nginx:/logs
      - sitemap:/sitemap

  mongo:
    build: ./mongo

  redis:
    image: redis:5.0.7

  app_en:
    build: 
      context: .
      args:
        branch: 'en'
    expose:
      - "3000"
      - "3010" 
      - "3011"
    environment:
      - MODULE=app
      - LANG=en
    depends_on:
      - "mongo"
      - "redis"
    restart: always
    volumes:
      - ./store:/store
      - ./logs/app_en:/logs

  app_ru:
    build: .
    expose:
      - "3000"
      - "3010"
      - "3011"
    environment:
      - MODULE=app
    depends_on:
      - "mongo"
      - "redis"
    restart: always
    volumes:
      - ./store:/store
      - ./logs/app_ru:/logs

  uploader:
    build: .
    expose:
      - "3001"
    environment:
      - MODULE=uploader
    depends_on:
      - "app_en"
    restart: always
    volumes:
      - ./store:/store
      - ./logs/uploader:/logs
      
  downloader:
    build: .
    expose:
      - "3002"
    environment:
      - MODULE=downloader
    depends_on:
      - "app_en"
    restart: always
    volumes:
      - ./store:/store:ro
      - ./logs/downloader:/logs
    
  sitemap:
    build: .
    environment:
      - MODULE=sitemap
    depends_on:
      - "app_en"
    restart: always
    volumes:
      - sitemap:/sitemap
      - ./logs/sitemap:/logs

volumes:
  sitemap:
